#  PIPELINE LOGIC
workflow:
    rules:
        - if: $CI_COMMIT_TAG =~ /^RT-\d+.\d+.\d+$/
          when: always
        - if: $CI_PIPELINE_SOURCE == "push"
          when: never
        # CASE I => First pipeline will run and than merge will done
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer" &&
              $CI_PIPELINE_SOURCE == 'merge_request_event' &&
              $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|release|bugfix)\/[a-z0-9._-]+$/
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "developer" &&
              $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat"  &&
              $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "uat" &&
              $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "pre-prod" &&
              $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always

          
        # CASE II => First Merge will be done than pipeline will start
        # - if: $CI_COMMIT_BRANCH == "pre-prod" || $CI_COMMIT_BRANCH == "uat"
        #   when: always

        # CASE III =>
        # - if: $CI_COMMIT_BRANCH == "pre-prod"  || $CI_COMMIT_BRANCH == "uat"
        # - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

    
        
#  Developer => When we are mergeing code from feature to Developer 
Feature to Developer:
  environment: development
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    
#  UAT => When we are mergeing code from Developer to UAT 
Developer to UAT:
  environment: UAT
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME

#  Pre-Production => When we are mergeing code from UAT to Pre-Production 
UAT to Pre-Prod:
  environment: Pre-Prod
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "pre-prod"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        
#  Master/Production => When we are mergeing code from Pre-Production to Prod 
# 
Prod Deployment:
  environment: Master
  rules:
    - if: $CI_COMMIT_TAG =~ /^RT-\d+.\d+.\d+$/
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
