#  PIPELINE INFRASTRUCTURE CODE
workflow:
    rules:
        - if: $CI_COMMIT_TAG =~ /^RT-\d+.\d+.\d+$/
          when: always
        - if: $CI_PIPELINE_SOURCE == "push"
          when: never
        # CASE I => First pipeline will run and than merge will done
        - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer" &&
              $CI_PIPELINE_SOURCE == 'merge_request_event' &&
              $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /^(feature|release|bugfix)\/[a-z0-9._-]+$/
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "developer" &&
              $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat"  &&
              $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always
        - if: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "uat" &&
              $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "pre-prod" &&
              $CI_PIPELINE_SOURCE == 'merge_request_event'
          when: always

          
        # CASE II => First Merge will be done than pipeline will start
        # - if: $CI_COMMIT_BRANCH == "pre-prod" || $CI_COMMIT_BRANCH == "uat"
        #   when: always

        # CASE III 
        # - if: $CI_COMMIT_BRANCH == "pre-prod"  || $CI_COMMIT_BRANCH == "uat"
        # - if: $CI_PIPELINE_SOURCE == 'merge_request_event'


stages:
  - "lint-check" 
  - "code-review" 
  - "code-deploy"
  - "end" 
        
# Feature to Developer  =>  merge code from feature|release|bugfix to Developer 
Feature to Developer [list-check]:
  stage: lint-check
  environment: development
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "lint-check"
Feature to Developer [code-review]:
  stage: code-review
  environment: development
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "code-review"
Feature to Developer [code-deploy]:
  stage: code-deploy
  environment: development
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "code-deploy"
Feature to Developer [end]:
  stage: end
  environment: development
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "developer"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "end"
    
# Developer to UAT =>  mergecode from Developer to UAT 
Developer to UAT [lint-test]:
  stage: lint-check
  environment: UAT
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "lint-test"
Developer to UAT [code-review]:
  stage: code-review
  environment: UAT
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "code-review"
Developer to UAT [code-deploy]:
  stage: code-deploy
  environment: UAT
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "uat"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        - echo "code-deploy"

#  UAT to Pre-Prod =>  merge code from UAT to Pre-Production 
UAT to Pre-Prod[lint-check]:
  stage: lint-check
  environment: Pre-Prod
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "pre-prod"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
UAT to Pre-Prod[code-review]:
  stage: code-review
  environment: Pre-Prod
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "pre-prod"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
UAT to Pre-Prod[code-deploy]:
  stage: code-deploy
  environment: Pre-Prod
  rules:
    - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "pre-prod"
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
        
#  Prod Deployment => mergeing code from pre-prod to prod/master, no pipeline will run.
#  Pipeline will run only when we create a new Tags on master branch.
Prod Deployment[lint-check]:
  stage: lint-check
  environment: Master
  rules:
    - if: $CI_COMMIT_TAG =~ /^RT-\d+.\d+.\d+$/
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
Prod Deployment[code-review]:
  stage: code-review
  environment: Master
  rules:
    - if: $CI_COMMIT_TAG =~ /^RT-\d+.\d+.\d+$/
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
Prod Deployment[code-deploy]:
  stage: code-deploy
  environment: Master
  rules:
    - if: $CI_COMMIT_TAG =~ /^RT-\d+.\d+.\d+$/
      when: on_success
  image: alpine
  script:
        - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME

